# Generated by Django 4.2.7 on 2025-09-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("transactions", "0001_initial"),
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_ledger_entries",
                to="transactions.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_ledger_entries",
                to="transactions.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentries",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="master.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentries",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.payment",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentries",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentries",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.salesorder",
            ),
        ),
    ]
