# Generated by Django 5.2.6 on 2025-10-02 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("vendor_bill", "Vendor Bill"),
                            ("sales_order", "Sales Order"),
                            ("customer_invoice", "Customer Invoice"),
                            ("payment", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("related_object_id", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="invoice",
            new_name="customer_invoice",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="bill",
            new_name="vendor_bill",
        ),
        migrations.RemoveField(
            model_name="customerinvoice",
            name="paid_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_mode",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="vendorbill",
            name="paid_date",
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank"), ("upi", "UPI")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vendorbill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="customerinvoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customerinvoice",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.salesorder",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="vendorbill",
            name="bill_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vendorbill",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.purchaseorder",
            ),
        ),
    ]
