# Generated by Django 5.2.6 on 2025-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_transaction_rename_invoice_payment_customer_invoice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order"),
                    ("vendor_bill", "Vendor Bill"),
                    ("sales_order", "Sales Order"),
                    ("customer_invoice", "Customer Invoice"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
