# Generated by Django 5.2.6 on 2025-10-04 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("transactions", "0003_purchaseorder_paid_purchaseorder_paid_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorbill",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="related_object_id",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="CustomerInvoice",
        ),
        migrations.DeleteModel(
            name="VendorBill",
        ),
    ]
