# Generated by Django 5.2.6 on 2025-10-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_remove_vendorbill_purchase_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
