# Generated by Django 4.2.7 on 2025-09-20 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorbill",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_vendor_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendorbill",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_bills",
                to="transactions.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="vendorbill",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"contact_type": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_bills",
                to="master.contact",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_items",
                to="master.product",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_items",
                to="transactions.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_items",
                to="master.tax",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sales_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"contact_type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_orders",
                to="master.contact",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="master.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="transactions.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_items",
                to="master.tax",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"contact_type": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="master.contact",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="transactions.customerinvoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vendor_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="transactions.vendorbill",
            ),
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_customer_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"contact_type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_invoices",
                to="master.contact",
            ),
        ),
        migrations.AddField(
            model_name="customerinvoice",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_invoices",
                to="transactions.salesorder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderitem",
            unique_together={("sales_order", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together={("purchase_order", "product")},
        ),
    ]
